name: CI

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x

    - name: Build race
      run: go build -race .

    - name: Build verb
      run: go build -v .
